// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetTrackLocalServiceClient is the client API for GetTrackLocalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetTrackLocalServiceClient interface {
	GetTrackLocal(ctx context.Context, in *Request, opts ...grpc.CallOption) (*TrackLocalResponse, error)
}

type getTrackLocalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetTrackLocalServiceClient(cc grpc.ClientConnInterface) GetTrackLocalServiceClient {
	return &getTrackLocalServiceClient{cc}
}

func (c *getTrackLocalServiceClient) GetTrackLocal(ctx context.Context, in *Request, opts ...grpc.CallOption) (*TrackLocalResponse, error) {
	out := new(TrackLocalResponse)
	err := c.cc.Invoke(ctx, "/proto.GetTrackLocalService/GetTrackLocal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetTrackLocalServiceServer is the server API for GetTrackLocalService service.
// All implementations must embed UnimplementedGetTrackLocalServiceServer
// for forward compatibility
type GetTrackLocalServiceServer interface {
	GetTrackLocal(context.Context, *Request) (*TrackLocalResponse, error)
	mustEmbedUnimplementedGetTrackLocalServiceServer()
}

// UnimplementedGetTrackLocalServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGetTrackLocalServiceServer struct {
}

func (UnimplementedGetTrackLocalServiceServer) GetTrackLocal(context.Context, *Request) (*TrackLocalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrackLocal not implemented")
}
func (UnimplementedGetTrackLocalServiceServer) mustEmbedUnimplementedGetTrackLocalServiceServer() {}

// UnsafeGetTrackLocalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetTrackLocalServiceServer will
// result in compilation errors.
type UnsafeGetTrackLocalServiceServer interface {
	mustEmbedUnimplementedGetTrackLocalServiceServer()
}

func RegisterGetTrackLocalServiceServer(s grpc.ServiceRegistrar, srv GetTrackLocalServiceServer) {
	s.RegisterService(&GetTrackLocalService_ServiceDesc, srv)
}

func _GetTrackLocalService_GetTrackLocal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetTrackLocalServiceServer).GetTrackLocal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GetTrackLocalService/GetTrackLocal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetTrackLocalServiceServer).GetTrackLocal(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// GetTrackLocalService_ServiceDesc is the grpc.ServiceDesc for GetTrackLocalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetTrackLocalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GetTrackLocalService",
	HandlerType: (*GetTrackLocalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTrackLocal",
			Handler:    _GetTrackLocalService_GetTrackLocal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
